fsowers/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('rocket.urls', namespace='rocket')),
]

rocket/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import HomeTemplateView,AboutTemplateView,register_view,contact_view

urlpatterns = [
	# url(r'^create$', views.home, name="create"),
	url(r'^$', HomeTemplateView.as_view(), name="home"),
	url(r'^about/$', AboutTemplateView.as_view(), name="about"),
	url(r'^contact/$', contact_view, name="contact"),
	url(r'^register/$', register_view, name="register"),


]

rocket/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
def upload_location(instance,filename):
	return "{0}/{1}/PaymentSnapshot/{2}".format(instance.owner,instance.account_number,filename)
	

class Subscriber(models.Model):
	GenderChoices = (
		('M', 'Male'),
		('F', 'Female')
		)
	first_name = models.CharField(max_length=20, default='',blank=False,null=False)
	last_name = models.CharField(max_length=20, default='',blank=False,null=False)
	sex = models.CharField(max_length=1, choices=GenderChoices, null=False, default='M')
	phone_number = models.CharField(max_length=11, default='', null=False, blank=True)
	email = models.CharField(max_length=30, default='', null=False, blank=False)
	Address = models.CharField(max_length=100, default='', null=False, blank=False)
	country = models.CharField(max_length=50, default='', null=False, blank=False)
	state = models.CharField(max_length=50, default='', null=False, blank=False)
	city = models.CharField(max_length=50, default='',null=False, blank=False)

	def __unicode__(self):
		return self.email

	def __str__(self):
		return self.email

class PaymentDetail(models.Model):
	PAYMENT_MEANS_CHOICE = (
		('B','Bank Deposit'),
		('A','ATM Transfer'),
		('M','Mobile Transfer'),
	)
	owner = models.OneToOneField(Subscriber)
	account_number = models.CharField(max_length=30, default='', null=False, blank=False)
	account_name = models.CharField(max_length=60, default='', null=False, blank=False)
	bank_name = models.CharField(max_length=30, default='', null=False, blank=False)
	payment_means = models.CharField(max_length=5, choices=PAYMENT_MEANS_CHOICE, default='B', null=False, blank=False)
	payment_snapshot = models.ImageField(upload_to=upload_location,null=True, blank=True,height_field="img_height", width_field="img_width")


	def __unicode__(self):
		return self.account_number

	def __str__(self):
		return self.account_number

rocket/forms.py
from django import forms
from .models import Subscriber



class ContactForm(forms.Form):
    email = forms.EmailField()
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"Name", 'type': 'text', 'name':"name"}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"Phone Number", 'type': 'text', 'name':"phone_number"}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control','placeholder':"Type your message here...", 'rows':'9', 'type': 'text', 'name':"phone_number"}))

class RegisterForm(forms.ModelForm):
	GenderChoices = (
		('M', 'Male'),
		('F', 'Female')
		)
	first_name =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"First Name", 'type': 'text', 'name':"first_name"}))
	last_name =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"Last Name", 'type': 'text', 'name':"last_name"}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',"type":"email","placeholder":"Email", "name":"email"}))
	sex = forms.ChoiceField(widget=forms.RadioSelect(attrs={'name':"option-yes"}),choices=GenderChoices)
	phone_number =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"Phone Number", 'type': 'text', 'name':"phone_number"}))
	Address =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"Address", 'type': 'text', 'name':"Address"}))
	country =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"Country", 'type': 'text', 'name':"country"}))
	state =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"State", 'type': 'text', 'name':"state"}))

	class Meta:
		model = Subscriber
		fields = [
			'first_name',
			'last_name',
			'sex',
			'phone_number',
			'email',
			'Address',
			'country',
			'state',
			'city',

		]

	def clean_email(self):
		email = self.cleaned_data.get('email')

		email_qs = Subscriber.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError('This email is already registered')

		return email

rocket/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
# Create your views here.
from .forms import RegisterForm,ContactForm
from .models import Subscriber


class HomeTemplateView(TemplateView):
	template_name = 'index.html'
	def get_context_data(self, **kwargs):
		context = super(HomeTemplateView, self).get_context_data(**kwargs)
		context['title'] = 'welcome to fsrst'

		return context



class AboutTemplateView(TemplateView):
	template_name = 'about.html'
	def get_context_data(self, **kwargs):
		context = super(AboutTemplateView, self).get_context_data(**kwargs)
		context['title'] = 'About'

		return context

def register_view(request):
	register = RegisterForm(request.POST or None,request.FILES or None)

	if register.is_valid():
		instance = register.save(commit=False)
		instance.save()
		return redirect('/')

	context = {
		'form' : register,
	}

	return render(request, 'register.html', context)

def contact_view(request):
    title_align_center=False
    title='contact us'
    form=ContactForm(request.POST or None)
    if form.is_valid():
        #METHOD 1
        #for key,value in form.cleaned_data.iteritems():
        #   print key +' : '+ value
        #METHOD 2
        #for key in form.cleaned_data:
        #    print key,form.cleaned_data.get(key)
        #METHOD 3
        #getting the data from the form fields
        form_name=form.cleaned_data.get("name")
        form_email=form.cleaned_data.get("email")
        form_phone_number=form.cleaned_data.get("phone_number")
        form_message=form.cleaned_data.get("message")
        
        #setting the parameters for the sendmail function
        subject='site contact form'
        contact_message='{0} {1} via {2}'.format(form_name,
        					form_message,
        					form_email
        					)
        from_email=settings.EMAIL_HOST_USER
        to_email=[from_email,'akinbamidayo@yahoo.com'] #this is field is a list
        #calling the send_mail function
        send_mail(subject,
        	contact_message,
        	from_email,
        	to_email,
        	fail_silently=False
        	)
        #print form.cleaned_data,email,name,phone_number,message
    context={
    	'form':form,
    	'title':title,
    	'title_align_center':title_align_center,
    
    }
    return render(request,'contact.html',context)

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">About</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-8 maincontent">
				<header class="page-header">
					<h1 class="page-title">About us</h1>
				</header>
				<h3>WHAT IS FSOWERS ROCKET SPEED TEAM?</h3>
				<p><img src="{% static 'assets/images/team_ads_3.jpg' %}" alt="" class="img-rounded img-thumbnail pull-right" width="300" >Fsowers rocket speed team are a group of fsowers members who commit to
growing their business with speed by registering for 12 accounts at
once with a one-time payment of #14,000 or more.</p>
				<p>Quos, aliquam nam velit impedit minus tenetur beatae voluptas facere sint pariatur! Voluptatibus, quisquam, error, est assumenda corporis inventore illo nesciunt iure aut dolor possimus repellat minima veniam alias eius!</p>
				<h3>FSOWERS ROCKET SPEED TEAM IS FOR THOSE WHO</h3>
				<ol>
					<li>Are too busy to get actively involved in networking</li>
					<li>Are not too good in talking to prospects or trying to convince
					people to join their team</li>
					<li>Want to move through the fsowers compensation plan Level with speed</li>
					<li>Desire to enjoy fsowers' juicy incentives and benefits.</li>
					<li>Long to enjoy a lifetime of residual income that exceeds their generation</li>
				</ol>
				<h3>HOW DOES IT WORK?</h3>
				<ol>
					<li>Each person registers for 12 fsowers accounts with a one-time
					payment of #14,000 (N12,000 for registration and N2,000 for logistics)
					or more.</li>
					<li>Each person is assigned a slot number (i.e. a position on the First
					Come First Served list). So the earlier you register and come on
					board, the better, because new team members get placed under you.</li>
					<li>50% Earning between level 3 upward that accrue to each person’s
					account at each stage will be re-invested to register more accounts
					(downlines) within the enclosed team</li>
					<li>Members attain each fsowers compensation stage (stages 1,  2, 3, 4
					e.t.c.) faster and earn more as the bonuses of stages 1 to 3 keep
					being re-invested</li>
					<li>Each member gets to enjoy the incentives (android phones, HP
					Laptops, Hyundai salon cars, monthly Salary, Paris trip e.t.c) that
					accrues to him / her at any stage faster than if he / she were
					personnally trying to recruit downlines</li>
				</ol> 
				<h3>BENEFITS OF JOINING FSOWERS ROCKET SPEED TEAM</h3>
				<ol>
					<li>You automatical enter level 3 in the space of 2 month or less</li>
					<li>We work to take you to level 4 in the space of 3 months or less &
					keep working (re-investing) to take you to the final level</li>
					<li>You don’t need to worry about bringing in people (downlines). We
					will do that for you.</li>
					<li>We auto-pilot your fsower accounts and give you feedbacks regularly.</li>
					<li>You don't need to convince anyone to come under you because your
					money works for you.</li>
					<li>Your money works for you while you sleep, creating residual income for life</li>
					<li>No risk involved as you get the money you invested and other benefits back.</li>
				</ol>
				<h3>WHAT IS THE PLAN OF THE TEAM IN GETTING DOWNLINES FOR US?</h3>
				<ol>
					<li>The 2000 naira for logistics is not a pocket money for the admin
					but the money is use to organize Mega Business Seminar Presentation.</li>
					<li>We get downlines to place other you through our social media platform such as online presentation.</li>
					<li>Through video presentation. And many more...</li>
				</ol>

				<p>Why wait, when you can tap into the anointing that produces Hyundai
				SUV? Join fsowers rocket speed today!<br>Call/WhatsApp: 08062893992</p>

				
				
			</article>
			<!-- /Article -->
			
			<!-- Sidebar -->
			<aside class="col-sm-4 sidebar sidebar-right">

				<div class="widget">
					<h4>Our Other Business</h4>
					<ul class="list-unstyled list-spaces">
						<li><a href="">Lorem ipsum dolor</a><br><span class="small text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, laborum.</span></li>
						<li><a href="">Totam, libero, quis</a><br><span class="small text-muted">Suscipit veniam debitis sed ipsam quia magnam eveniet perferendis nisi.</span></li>
						<li><a href="">Enim, sequi dignissimos</a><br><span class="small text-muted">Reprehenderit illum quod unde quo vero ab inventore alias veritatis.</span></li>
						<li><a href="">Suscipit, consequatur, aut</a><br><span class="small text-muted">Sed, mollitia earum debitis est itaque esse reiciendis amet cupiditate.</span></li>
						<li><a href="">Nam, illo, veritatis</a><br><span class="small text-muted">Delectus, sapiente illo provident quo aliquam nihil beatae dignissimos itaque.</span></li>
					</ul>
				</div>

				<div class="widget">
					<h4>Testimonies</h4>
					<div class="h-caption"><h4><img src="{% static 'assets/images/team_ads_4.jpg' %}" class="img img-thumbnail">Winner1</h4></div>
					<div class="h-body text-center">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque aliquid adipisci aspernatur. Soluta quisquam dignissimos earum quasi voluptate. Amet, dignissimos, tenetur vitae dolor quam iusto assumenda hic reprehenderit?</p>
					</div>
					<div class="h-caption"><h4><img src="{% static 'assets/images/team_ads_6.jpg' %}" class="img img-thumbnail">Winner2</h4></div>
					<div class="h-body text-center">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque aliquid adipisci aspernatur. Soluta quisquam dignissimos earum quasi voluptate. Amet, dignissimos, tenetur vitae dolor quam iusto assumenda hic reprehenderit?</p>
					</div>
				</div>

			</aside>
			<!-- /Sidebar -->

		</div>
	</div>	<!-- /container -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Akinbami Dayo (Dakins Solution)">
	
	<title>Welcome - Rocket Speed Team</title>

	<link rel="shortcut icon" href="{% static 'assets/images/gt_favicon.png' %}">
	
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap-theme.css' %}" media="screen" >
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">


	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="assets/js/html5shiv.js"></script>
	<script src="assets/js/respond.min.js"></script>
	<![endif]-->
</head>

<body class="home">
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="{% url 'rocket:home' %}">Rocket Speeed Team</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li class="active"><a href="{% url 'rocket:home' %}">Home</a></li>
					<li><a href="{% url 'rocket:about' %}">About</a></li>
					<li><a href="#faq">FAQ</a></li>
					<li><a href="#">FSowers</a></li>
					<li><a href="{% url 'rocket:contact' %}">Contact</a></li>
					<li><a class="btn" href="{% url 'rocket:register' %}">SIGN UP</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div> 
	<!-- /.navbar -->
	{% block content %}

	{% endblock	%}

	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					
					<div class="col-md-3 widget">
						<h3 class="widget-title">Contact</h3>
						<div class="widget-body">
							<p>+234 8186737195<br>
								<a href="mailto:#">akinbamizacheus@gmail.com</a><br>
							</p>	
						</div>
					</div>

					<div class="col-md-3 widget">
						<h3 class="widget-title">Follow me</h3>
						<div class="widget-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								<a href=""><i class="fa fa-dribbble fa-2"></i></a>
								<a href=""><i class="fa fa-github fa-2"></i></a>
								<a href=""><i class="fa fa-facebook fa-2"></i></a>
							</p>	
						</div>
					</div>

					<div class="col-md-6 widget">
						<h3 class="widget-title">Fact</h3>
						<div class="widget-body">
							<p>You will agree with me that the challenge in network biz (mlm) is the
							ability to recruit downlines, build your matrix and balance your legs
							at the same time..</p>
							<p>The most challenging is recruitment.... If your downlines are not able
							to bring in people, your earning and your business stops which can be
							very frustrating.</p>
							<p>In order to conquer this challenge, we came up with this group called
							<h2>FSOWERS ROCKET SPEED TEAM.</h2>

							Which means:
							<h2>REGISTER
							RELAX AND
							CASH your earning$$$$</h2></p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="#">Home</a> | 
								<a href="about.html">About</a> |
								<a href="sidebar-right.html">Sidebar</a> |
								<a href="contact.html">Contact</a> |
								<b><a href="signup.html">Sign up</a></b>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2017, Dakin. Designed by Dakins Solution
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>	
		




	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="{% static 'assets/js/headroom.min.js' %}"></script>
	<script src="{% static 'assets/js/jQuery.headroom.min.js' %}"></script>
	<script src="{% static 'assets/js/template.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">About</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-9 maincontent">
				<header class="page-header">
					<h1 class="page-title">Contact us</h1>
				</header>
				
				<p>
					We’d love to hear from you. Interested in working together? Fill out the form below with some info about your project and I will get back to you as soon as I can. Please allow a couple days for me to respond.
				</p>
				<br>
					<form method="POST" action="">{% csrf_token %}
						<div class="row">
							<div class="col-sm-4">
								{{ form.name }}
							</div>
							<div class="col-sm-4">
								{{ form.email }}
							</div>
							<div class="col-sm-4">
								{{ form.phone_number }}
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-sm-12">
								{{ form.message }}
								
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-sm-6">
								<label class="checkbox"><input type="checkbox"> Sign up for newsletter</label>
							</div>
							<div class="col-sm-6 text-right">
								<input class="btn btn-action" type="submit" value="Send message">
							</div>
						</div>
					</form>

			</article>
			<!-- /Article -->
			
			<!-- Sidebar -->
			<aside class="col-sm-3 sidebar sidebar-right">

				<div class="widget">
					<h4>Address</h4>
					<address>
						Premier University of Ibadan
					</address>
					<h4>Phone:</h4>
					<address>
						08062893992
					</address>
				</div>

			</aside>
			<!-- /Sidebar -->

		</div>
	</div>	<!-- /container -->
	
	<section class="container-full top-space">
		<div id="map"></div>
	</section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block content %}
	<!-- Header -->
	<header id="head">
		<div class="container">
			<div class="row">
				<p> <a class="btn btn-action btn-lg" href="{% url 'rocket:register' %}" role="button">SignUp NOW</a></p>
			</div>
		</div>
	</header>
	<!-- /Header -->

	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">Conquer the challenge of recruiting downline and empower your MLM business with automatic progress</h2>
	</div>
	<!-- /Intro-->
		
	<!-- Highlights - jumbotron -->
	<div class="jumbotron top-space">
		<div class="container">
			
			<h3 class="text-center thin">Reasons to invest in Rocket Speed Team</h3>
			
			<div class="row">
				<div class="col-md-4 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-cogs fa-5"></i>Transparency</h4></div>
					<div class="h-body text-center">
						<p>You will be given updates on the progress of your FSowers account.</p>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-flash fa-5"></i>Spead</h4></div>
					<div class="h-body text-center">
						<p>Your downline will increase faster compared to ordinary account. </p>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-smile-o fa-5"></i>Admin's support</h4></div>
					<div class="h-body text-center">
						<p>24/7 Admin support will be provided and all your questions will be answered. </p>
					</div>
				</div>
			</div> <!-- /row  -->
		
		</div>
	</div>
	<!-- /Highlights -->

	<!-- container -->
	<div class="container">

		<h2 class="text-center top-space" id='faq'>Frequently Asked Questions</h2>
		<br>

		<div class="row">
			<div class="col-sm-6">
				<h3>Which code editor would you recommend?</h3>
				<p>I'd highly recommend you <a href="http://www.sublimetext.com/">Sublime Text</a> - a free to try text editor which I'm using daily. Awesome tool!</p>
			</div>
			<div class="col-sm-6">
				<h3>Nice header. Where do I find more images like that one?</h3>
				<p>
					Well, there are thousands of stock art galleries, but personally, 
					I prefer to use photos from these sites: <a href="http://unsplash.com">Unsplash.com</a> 
					and <a href="http://www.flickr.com/creativecommons/by-2.0/tags/">Flickr - Creative Commons</a></p>
			</div>
		</div> <!-- /row -->

		<div class="row">
			<div class="col-sm-6">
				<h3>Can I use it to build a site for my client?</h3>
				<p>
					Yes, you can. You may use this template for any purpose, just don't forget about the <a href="http://creativecommons.org/licenses/by/3.0/">license</a>, 
					which says: "You must give appropriate credit", i.e. you must provide the name of the creator and a link to the original template in your work. 
				</p>
			</div>
			<div class="col-sm-6">
				<h3>Can you customize this template for me?</h3>
				<p>Yes, I can. Please drop me a line to sergey-at-pozhilov.com and describe your needs in details. Please note, my services are not cheap.</p>
			</div>
		</div> <!-- /row -->

		<div class="jumbotron top-space">
			<h4>WELCOME TO THE WORLD OF FSOWERS NETWORK, FULL OF OPPORTUNITIES.</h4>
			<h5> A
brand new PURE ONLINE MLM BUSINESS. It is simple and affordable. It is
one of its kind in uniqueness and transparency. If u are looking for d
most lucrative MLM business come to the FSOWERS network. A first class
and world famous networking business of our time.
Also will I warmly WELCOME u to FSOWERS ROCKET SPEED TEAM...</h5>
			<h4>WHAT IS FSOWERS?</h4>
			<h5>FSOWERS is the short form of FUTURE SOWERS NETWORK Business. FUTURE
			SOWERS NETWORK.</h5>
			
			<h5>The FSowers Network Money Making System is an online business which is
			allowing *FSOWERS NETWORK*</h5>
     		<p class="text-right"><a class="btn btn-primary btn-large">Learn more »</a></p>
  		</div>

</div>	<!-- /container -->
	
	<!-- Social links. @TODO: replace by link/instructions in template -->
	<section id="social">
		<div class="container">
			<div class="wrapper clearfix">
				<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_linkedin_counter"></a>
				<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
				</div>
				<!-- AddThis Button END -->
			</div>
		</div>
	</section>
	<!-- /social links -->


	{% endblock %}

templates/register.html
{% extends 'base.html' %}


{% block content %}

	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">Registration</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Register a new account</h3>
							<hr>

							<form method="POST" action="">{% csrf_token %}
								<div class="top-margin">
									<label>First Name</label>
									{{ form.first_name }}
								</div>
								<div class="top-margin">
									<label>Last Name</label>
									{{ form.last_name }}
								</div>
								<div class="top-margin">
									<label>Email Address <span class="text-danger">*</span></label>
									{{ form.email }}
								</div>

								<div class="row top-margin">
									<div class="col-sm-6">
										<label class="checkbox-inline">
											{% for i in form.sex %}
												{{ i }}
											{% endfor %}
										</label>
									</div>
									<div class="col-sm-6">
										<label>Phone <span class="text-danger">*</span></label>
										{{ form.phone_number }}
									</div>
								</div>
								<div class="top-margin">
									<label>Address <span class="text-danger">*</span></label>
									{{ form.Address }}
								</div>
								<div class="top-margin">
									<label>Country <span class="text-danger">*</span></label>
									{{ form.country }}
								</div>
								<div class="top-margin">
									<label>State <span class="text-danger">*</span></label>
									{{ form.state }}
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<label class="checkbox">
											<input type="checkbox"> 
											I've read the <a href="page_terms.html">Terms and Conditions</a>
										</label>                        
									</div>
									<div class="col-lg-4 text-right">
										<input class="btn btn-default  btn-action text-center pull-right" type="submit" value="Register">
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
	
{% endblock %}